version: "3"

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      # resources needed for mongodb
      - ./db:/home/mongodb
      - ./scripts/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    restart: always
    environment:
      MONGO_INITDB_USERNAME: "$MONGO_INITDB_USERNAME"
      MONGO_INITDB_PASSWORD: "$MONGO_INITDB_PASSWORD"
      MONGO_REPLICA_HOST: mongo
      MONGO_REPLICA_PORT: 27017
    networks:
      - default

  api:
    build:
      context: .
      target: dev # docker-compose is only used for local development
      dockerfile: Dockerfile
    command: /bin/sh -c "cargo watch -x run"
    volumes:
      # use files from local environment for development
      - .:/app
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongodb:27017
    networks:
      - default

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "$MONGO_INITDB_ROOT_USERNAME"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "$MONGO_INITDB_ROOT_PASSWORD"
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    networks:
      - default

networks:
  default:
    driver: bridge
