# For testing, we don't need mongo-express, and we want to run the tests in a clean
# environment, so we don't use any of the local files as volumes
version: "3"

services:
  mongodb:
    container_name: restaurant-mongodb-test
    image: mongo
    ports:
      - "27018:27018"
    volumes:
      # resources needed for mongodb
      - ./db/test:/home/mongodb
      - ./scripts/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    restart: always
    environment:
      MONGO_INITDB_USERNAME: "$MONGO_INITDB_USERNAME"
      MONGO_INITDB_PASSWORD: "$MONGO_INITDB_PASSWORD"
      MONGO_REPLICA_HOST: mongodb-test
      MONGO_REPLICA_PORT: 27018
    networks:
      - test

  api:
    container_name: restaurant-api-test
    build:
      context: .
      target: dev # docker-compose is only used for local development
      dockerfile: ./server/Dockerfile
    command: /bin/sh -c "cargo test"
    stdin_open: true
    tty: true
    ports:
      - "8088:8088"
    depends_on:
      - mongodb
    environment:
      - PORT=8088
      - MONGO_URI=mongodb://restaurant-mongodb-test:27018/?authSource=admin
    networks:
      - test

networks:
  test:
    driver: bridge

